language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.4

arch:
  - amd64
  - arm64

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "dn5Irr/svB2d/iouvSxxoe2SEAWlPUlkNlGWScngWhqSp+kEJ8p3ubQG0ogCK0vGGHPwUYXfIQvHQ8oSc2Z4na8rIwZqvkJnxYYKvPLZpweKhb+xQbpjPwDwEycFDxT+y7mPnRLKRDtdmcuRqMQh8gnxb6TMY9xqlCCvnTfwTmI="
    - coverity_scan_run_condition='\( "$CC" = "gcc" \) -a \( $USECMAKE -eq 0 \) -a \( "$TRAVIS_OS_NAME" = "linux" \) -a \( "$(uname -i)" = "x86_64" \)'
    - coverity_scan_script_test_mode=false
    # Various conditions where the Travis CI scripts should behave differently
    - is_coverity_branch='\( "$TRAVIS_BRANCH" = "coverity_scan" \)'
    - is_valid_config='\( ! '"$is_coverity_branch"' \) -o \( '"$coverity_scan_run_condition"' \)'
    - is_valid_osx='\( "$TRAVIS_OS_NAME" = "osx" \) -a \( '"$is_valid_config"' \)'
    - is_valid_linux='\( "$TRAVIS_OS_NAME" = "linux" \) -a \( '"$is_valid_config"' \)'
    - is_amd64='\( "$(uname -i)" = "x86_64" \)'
    - is_arm64='\( "$(uname -i)" = "aarch64" \)'
    - is_notcoverity_autot='\( ! '"$is_coverity_branch"' \) -a \( $USECMAKE -eq 0 \)'
    - is_notcoverity_cmake='\( ! '"$is_coverity_branch"' \) -a \( $USECMAKE -eq 1 \)'
  jobs:
    # Let's test both our autoconf and CMake build system
    - USECMAKE=0
    - USECMAKE=1

jobs:
  exclude:
    # On Linux, we only need to test one compiler with both autools and CMake.
    # This gives us three builds on Linux: autotools+gcc, autotools+clang, CMake+gcc
    - compiler: clang
      os: linux
      env: USECMAKE=1
    # On macOS, gcc is deprecated, so we only build with clang there.
    # This gives us two builds on macOS: autotools+clang, CMake+clang
    - compiler: gcc
      os: osx
    # Do not compile for arm64 on osx yet.
    - arch: arm64
      os: osx
    # Only build the Coverity Scan branch with the Linux amd64 gcc autotools VM
    - if: branch = coverity_scan
      os: osx
    - if: branch = coverity_scan
      arch: arm64
    - if: branch = coverity_scan
      env: USECMAKE=1
    - if: branch = coverity_scan
      compiler: clang

script:
  # environment
  - export CXXFLAGS="$CXXFLAGS -O2 -ggdb"
  - if eval [ $is_valid_osx ]; then export CXXFLAGS="$CXXFLAGS -isystem /usr/local/include"; fi
  - if eval [ $is_valid_osx -a $is_notcoverity_autot ]; then export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/qt/lib/pkgconfig"; fi
  # autotools build system: ./autogen.sh && ./configure && make && make check
  - if eval [ $is_notcoverity_autot ]; then ./autogen.sh; fi
  - if eval [ $is_notcoverity_autot ]; then ./configure || (cat config.log; exit 1); fi
  - if eval [ $is_notcoverity_autot ]; then make -j4; fi
  - if eval [ $is_notcoverity_autot ]; then echo "" > test-suite.log; make -j4 check || (cat test-suite.log; exit 1); fi
  # CMake build system: cmake . && make && make check
  - if eval [ $is_notcoverity_cmake ]; then cmake .; fi
  - if eval [ $is_notcoverity_cmake ]; then make -j4; fi
  - if eval [ $is_notcoverity_cmake ]; then make -j4 check; fi

addons:
  apt:
    packages:
    - libboost-all-dev
    - zlib1g-dev
    - liblzma-dev
    - libopenal-dev
    - libmad0-dev
    - libvorbis-dev
    - qtbase5-dev
    - libqt5gui5
    - libqt5multimedia5
    - qtmultimedia5-dev
    - libqt5multimediawidgets5
    - libgl1
    - libgl-dev
    - libglu-dev
  homebrew:
    packages:
    - zlib
    - xz
    - qt
    - openal-soft
    - mad
    - faad2
    - libvorbis
  coverity_scan:
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis_coverity.sh
    project:
      name: $TRAVIS_REPO_SLUG
    notification_email: drmccoy@drmccoy.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4 check"
    branch_pattern: coverity_scan

notifications:
  irc:
    channels:
      - secure: "U+V3MgGroSCh5ck+utcDk8cQSqUpoRxdRlTba5473Jbk+8DYCbq3pNHLJZeLn+OtEb32CHsmZGW8NBXZ3kw0vbjaMxDrZoUfNEqkf7f78q7PS+32NQN0GJ+G6bytRwimAeT5KsKkyYmYRjBF0m8uNUcPJsLsEJRvuasA6RhEmA8="
    on_success: change
    on_failure: always
    use_notice: true
